# Generated by Django 2.2 on 2019-04-11 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='videos_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
