# Generated by Django 2.2 on 2019-05-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='comments',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to='comments.Comment'),
        ),
    ]
