# Generated by Django 2.2 on 2019-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='videos_subjects', to='subjects.Subject'),
        ),
    ]
