# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-30 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='document',
            new_name='file',
        ),
    ]
