# Generated by Django 2.2 on 2019-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190506_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='watched',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
