# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20190402_0012'),
        ('comments', '0004_auto_20190329_1757'),
        ('accounts', '0010_auto_20190329_1757'),
        ('videos', '0002_auto_20190330_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
        migrations.CreateModel(
            name='UsersVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_watched', models.IntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('comment', models.ManyToManyField(blank=True, related_name='video_coments', to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'users_videos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersvideos',
            unique_together=set([('user', 'video')]),
        ),
    ]
