# Generated by Django 2.2 on 2019-05-02 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_auto_20190502_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersVideos',
            new_name='UserVideo',
        ),
    ]
