# Generated by Django 2.2 on 2019-04-29 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_auto_20190411_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='videos_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
