# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-02 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20190402_0012'),
        ('videos', '0003_auto_20190402_0012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectsvideos',
            unique_together=set([('subject', 'video')]),
        ),
        migrations.AlterModelTable(
            name='subjectsvideos',
            table='subjects_videos',
        ),
    ]
