# Generated by Django 2.2.3 on 2019-10-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190624_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_likes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
