# Generated by Django 2.2 on 2019-05-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20190508_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislikes',
            new_name='dislikes',
        ),
    ]
