# Generated by Django 2.2.3 on 2019-10-11 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_video_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_likes',
            field=models.BigIntegerField(default=0, verbose_name=django.db.models.aggregates.Count(models.ManyToManyField(blank=True, related_name='videos_likes', to=settings.AUTH_USER_MODEL))),
        ),
    ]
