# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-04 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20190404_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersvideos',
            options={},
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='added',
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='edited',
        ),
    ]
