# Generated by Django 2.2 on 2019-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20170819_1127'),
        ('videos', '0006_auto_20190515_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_rating', to='ratings.Rating'),
        ),
    ]
