# Generated by Django 2.2.3 on 2019-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_dislikes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='num_likes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
