# Generated by Django 2.2 on 2019-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.ManyToManyField(related_name='video_rating', to='ratings.Rating'),
        ),
    ]
