# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20190404_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersvideos',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
