# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_usersvideos_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to='accounts.UserProfile'),
        ),
    ]
