# Generated by Django 2.2 on 2019-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20190515_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
