# Generated by Django 2.2 on 2019-05-17 23:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('videos', '0009_video_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservideo',
            unique_together={('user', 'video', 'comments')},
        ),
    ]
