# Generated by Django 2.2 on 2019-05-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20190518_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
    ]
