# Generated by Django 2.1.2 on 2019-04-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20190407_2232'),
        ('videos', '0012_video_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersvideos',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='comment',
        ),
        migrations.AddField(
            model_name='usersvideos',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='video_comments', to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='usersvideos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_videos', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usersvideos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_videos', to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='videos_liked', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='parent',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterModelTable(
            name='subjectsvideos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usersvideos',
            table=None,
        ),
    ]
