# Generated by Django 2.2 on 2019-04-29 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='comment_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
