# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='added',
        ),
    ]
