# Generated by Django 2.2.1 on 2019-06-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_rating', to=settings.AUTH_USER_MODEL)),
                ('user_rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_rated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='rating_beetween_users', through='accounts.RatingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
