# Generated by Django 2.2.1 on 2019-06-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190611_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinguser',
            name='user_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratinguser',
            name='user_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
