# Generated by Django 2.2.3 on 2019-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190611_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='users_interests_subjects', to='subjects.Subject'),
        ),
    ]
