# Generated by Django 2.2.3 on 2019-10-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_num_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='num_followers',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
