# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170629_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
