# Generated by Django 2.1.2 on 2019-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20190407_2232'),
        ('accounts', '0010_auto_20190329_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='users', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followers_+', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
