# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0004_auto_20190329_1757'),
        ('accounts', '0010_auto_20190329_1757'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('rector', models.CharField(blank=True, max_length=50, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'center',
            },
        ),
        migrations.CreateModel(
            name='CentersDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Center')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'centers_degrees',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='DegreesSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Degree')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'degrees_subjects',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectsVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'subject_videos',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(choices=[(b'PU', b'Public'), (b'PR', b'Private')], max_length=2, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UsersSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'users_subjects',
            },
        ),
        migrations.CreateModel(
            name='UsersVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_watched', models.IntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('comment', models.ManyToManyField(blank=True, related_name='video_coments', to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'ordering': ['-added'],
                'db_table': 'users_videos',
            },
        ),
        migrations.AddField(
            model_name='degreessubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='centersdegrees',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Degree'),
        ),
        migrations.AddField(
            model_name='center',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.University'),
        ),
        migrations.AlterUniqueTogether(
            name='usersvideos',
            unique_together=set([('user', 'video')]),
        ),
        migrations.AlterUniqueTogether(
            name='userssubjects',
            unique_together=set([('user', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectsvideos',
            unique_together=set([('subject', 'video')]),
        ),
        migrations.AlterUniqueTogether(
            name='degreessubjects',
            unique_together=set([('degree', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='centersdegrees',
            unique_together=set([('center', 'degree')]),
        ),
    ]
