# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='subject_videos', to='videos.Video'),
        ),
    ]
