# Generated by Django 2.2.3 on 2019-08-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20190624_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
