# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('subjects', '0003_remove_subject_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectsvideos',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subjectsvideos',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectsvideos',
            name='video',
        ),
        migrations.AddField(
            model_name='subject',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='subject_videos', to='videos.Video'),
        ),
        migrations.DeleteModel(
            name='SubjectsVideos',
        ),
    ]
