# Generated by Django 2.2.3 on 2019-08-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_university_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
