# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-01 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20190329_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersvideos',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersvideos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video',
        ),
        migrations.DeleteModel(
            name='UsersVideos',
        ),
    ]
