# Generated by Django 2.1.2 on 2019-04-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20190402_0012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centersdegrees',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='centersdegrees',
            name='center',
        ),
        migrations.RemoveField(
            model_name='centersdegrees',
            name='degree',
        ),
        migrations.AlterUniqueTogether(
            name='userssubjects',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userssubjects',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userssubjects',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='degreessubjects',
            options={},
        ),
        migrations.AddField(
            model_name='degree',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Center'),
        ),
        migrations.AlterField(
            model_name='university',
            name='domain',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2, null=True),
        ),
        migrations.AlterModelTable(
            name='center',
            table=None,
        ),
        migrations.AlterModelTable(
            name='degree',
            table=None,
        ),
        migrations.AlterModelTable(
            name='degreessubjects',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='university',
            table=None,
        ),
        migrations.DeleteModel(
            name='CentersDegrees',
        ),
        migrations.DeleteModel(
            name='UsersSubjects',
        ),
    ]
